services:
  localdb:
    image: postgres:15.1 # you can pick the most recent version available
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=sophia_bergamo  
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=instituto

  testdb:
    image: postgres:15.1
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=sophia_bergamo
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=instituto